<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\WithdrawMethod;
use Illuminate\Database\Seeder;

class WithdrawMethodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $withdrawMethods = [
            // USDT Networks
            [
                'form_id' => 0,
                'name' => 'USDT (BEP-20)',
                'method_key' => 'usdtbep20',
                'min_limit' => 10.00,
                'max_limit' => 50000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 2.00,
                'currency' => 'USDT',
                'instructions' => 'Please provide your BEP-20 compatible USDT wallet address. Network: Binance Smart Chain (BSC)',
                'sort_order' => 1,
                'description' => 'USDT on Binance Smart Chain (BEP-20) - Fast and low fees',
                'icon' => 'fas fa-coins',
                'processing_time' => '1-5 minutes',
                'status' => 1,
                'min_amount' => 10.00,
                'max_amount' => 50000.00,
                'daily_limit' => 10000.00,
                'charge_type' => 'percent',
                'charge' => 2.00,
            ],
            [
                'form_id' => 0,
                'name' => 'USDT (TRC-20)',
                'method_key' => 'usdttrc20',
                'min_limit' => 5.00,
                'max_limit' => 35000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 1.50,
                'currency' => 'USDT',
                'instructions' => 'Please provide your TRC-20 compatible USDT wallet address. Network: TRON (TRC-20)',
                'sort_order' => 2,
                'description' => 'USDT on TRON network (TRC-20) - Ultra low fees',
                'icon' => 'fas fa-bolt',
                'processing_time' => '1-3 minutes',
                'status' => 1,
                'min_amount' => 5.00,
                'max_amount' => 35000.00,
                'daily_limit' => 9000.00,
                'charge_type' => 'fixed',
                'charge' => 1.00,
            ],
            [
                'form_id' => 0,
                'name' => 'USDT (ERC-20)',
                'method_key' => 'usdterc20',
                'min_limit' => 10.00,
                'max_limit' => 25000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 3.00,
                'currency' => 'USDT',
                'instructions' => 'Please provide your ERC-20 compatible USDT wallet address. Network: Ethereum (ERC-20)',
                'sort_order' => 3,
                'description' => 'USDT on Ethereum network (ERC-20)',
                'icon' => 'fab fa-ethereum',
                'processing_time' => '5-30 minutes',
                'status' => 1,
                'min_amount' => 10.00,
                'max_amount' => 25000.00,
                'daily_limit' => 7000.00,
                'charge_type' => 'fixed',
                'charge' => 5.00,
            ],
            
            // Major Cryptocurrencies
            [
                'form_id' => 0,
                'name' => 'Bitcoin (BTC)',
                'method_key' => 'bitcoin',
                'min_limit' => 20.00,
                'max_limit' => 100000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 2.50,
                'currency' => 'BTC',
                'instructions' => 'Please provide your Bitcoin wallet address.',
                'sort_order' => 4,
                'description' => 'Bitcoin cryptocurrency withdrawal',
                'icon' => 'fab fa-bitcoin',
                'processing_time' => '30 minutes - 2 hours',
                'status' => 1,
                'min_amount' => 20.00,
                'max_amount' => 100000.00,
                'daily_limit' => 25000.00,
                'charge_type' => 'fixed',
                'charge' => 10.00,
            ],
            [
                'form_id' => 0,
                'name' => 'Ethereum (ETH)',
                'method_key' => 'ethereum',
                'min_limit' => 15.00,
                'max_limit' => 75000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 2.00,
                'currency' => 'ETH',
                'instructions' => 'Please provide your Ethereum wallet address.',
                'sort_order' => 5,
                'description' => 'Ethereum cryptocurrency withdrawal',
                'icon' => 'fab fa-ethereum',
                'processing_time' => '5-20 minutes',
                'status' => 1,
                'min_amount' => 15.00,
                'max_amount' => 75000.00,
                'daily_limit' => 20000.00,
                'charge_type' => 'fixed',
                'charge' => 8.00,
            ],
            [
                'form_id' => 0,
                'name' => 'Binance Coin (BNB)',
                'method_key' => 'bnb',
                'min_limit' => 10.00,
                'max_limit' => 50000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 1.50,
                'currency' => 'BNB',
                'instructions' => 'Please provide your BNB wallet address (BSC network).',
                'sort_order' => 6,
                'description' => 'Binance Coin (BNB) withdrawal',
                'icon' => 'fas fa-coins',
                'processing_time' => '1-5 minutes',
                'status' => 1,
                'min_amount' => 10.00,
                'max_amount' => 50000.00,
                'daily_limit' => 15000.00,
                'charge_type' => 'percent',
                'charge' => 1.50,
            ],
            [
                'form_id' => 0,
                'name' => 'Litecoin (LTC)',
                'method_key' => 'litecoin',
                'min_limit' => 10.00,
                'max_limit' => 30000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 1.00,
                'currency' => 'LTC',
                'instructions' => 'Please provide your Litecoin wallet address.',
                'sort_order' => 7,
                'description' => 'Litecoin cryptocurrency withdrawal',
                'icon' => 'fas fa-coins',
                'processing_time' => '15-45 minutes',
                'status' => 1,
                'min_amount' => 10.00,
                'max_amount' => 30000.00,
                'daily_limit' => 12000.00,
                'charge_type' => 'fixed',
                'charge' => 2.00,
            ],
            [
                'form_id' => 0,
                'name' => 'Cardano (ADA)',
                'method_key' => 'cardano',
                'min_limit' => 5.00,
                'max_limit' => 25000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 1.00,
                'currency' => 'ADA',
                'instructions' => 'Please provide your Cardano wallet address.',
                'sort_order' => 8,
                'description' => 'Cardano (ADA) cryptocurrency withdrawal',
                'icon' => 'fas fa-coins',
                'processing_time' => '5-15 minutes',
                'status' => 1,
                'min_amount' => 5.00,
                'max_amount' => 25000.00,
                'daily_limit' => 8000.00,
                'charge_type' => 'fixed',
                'charge' => 1.50,
            ],
            [
                'form_id' => 0,
                'name' => 'Polygon (MATIC)',
                'method_key' => 'polygon',
                'min_limit' => 5.00,
                'max_limit' => 20000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 1.00,
                'currency' => 'MATIC',
                'instructions' => 'Please provide your Polygon wallet address.',
                'sort_order' => 9,
                'description' => 'Polygon (MATIC) cryptocurrency withdrawal',
                'icon' => 'fas fa-coins',
                'processing_time' => '1-5 minutes',
                'status' => 1,
                'min_amount' => 5.00,
                'max_amount' => 20000.00,
                'daily_limit' => 6000.00,
                'charge_type' => 'fixed',
                'charge' => 1.00,
            ],
            
            // Digital Wallets & E-money
            [
                'form_id' => 0,
                'name' => 'PayPal',
                'method_key' => 'paypal',
                'min_limit' => 5.00,
                'max_limit' => 10000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 3.50,
                'currency' => 'USD',
                'instructions' => 'Please provide your PayPal email address.',
                'sort_order' => 10,
                'description' => 'PayPal instant transfer',
                'icon' => 'fab fa-paypal',
                'processing_time' => '1-24 hours',
                'status' => 1,
                'min_amount' => 5.00,
                'max_amount' => 10000.00,
                'daily_limit' => 5000.00,
                'charge_type' => 'percent',
                'charge' => 3.50,
            ],
            [
                'form_id' => 0,
                'name' => 'Skrill',
                'method_key' => 'skrill',
                'min_limit' => 10.00,
                'max_limit' => 8000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 3.00,
                'currency' => 'USD',
                'instructions' => 'Please provide your Skrill email address.',
                'sort_order' => 11,
                'description' => 'Skrill e-wallet transfer',
                'icon' => 'fas fa-wallet',
                'processing_time' => '1-24 hours',
                'status' => 1,
                'min_amount' => 10.00,
                'max_amount' => 8000.00,
                'daily_limit' => 3000.00,
                'charge_type' => 'percent',
                'charge' => 3.00,
            ],
            [
                'form_id' => 0,
                'name' => 'Perfect Money',
                'method_key' => 'perfect_money',
                'min_limit' => 5.00,
                'max_limit' => 15000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 2.00,
                'currency' => 'USD',
                'instructions' => 'Please provide your Perfect Money account number.',
                'sort_order' => 12,
                'description' => 'Perfect Money e-currency transfer',
                'icon' => 'fas fa-money-check-alt',
                'processing_time' => '1-6 hours',
                'status' => 1,
                'min_amount' => 5.00,
                'max_amount' => 15000.00,
                'daily_limit' => 8000.00,
                'charge_type' => 'fixed',
                'charge' => 2.00,
            ],
            
            // International Fiat Currencies
            [
                'form_id' => 0,
                'name' => 'USD Bank Transfer',
                'method_key' => 'usd_bank',
                'min_limit' => 50.00,
                'max_limit' => 50000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 2.50,
                'currency' => 'USD',
                'instructions' => 'Please provide your USD bank account details including SWIFT code and account number.',
                'sort_order' => 13,
                'description' => 'USD Wire Transfer to your bank account',
                'icon' => 'fas fa-university',
                'processing_time' => '1-3 business days',
                'status' => 1,
                'min_amount' => 50.00,
                'max_amount' => 50000.00,
                'daily_limit' => 15000.00,
                'charge_type' => 'fixed',
                'charge' => 25.00,
            ],
            [
                'form_id' => 0,
                'name' => 'EUR Bank Transfer',
                'method_key' => 'eur_bank',
                'min_limit' => 50.00,
                'max_limit' => 45000.00,
                'fixed_charge' => 0.00,
                'rate' => 0.92,
                'percent_charge' => 2.00,
                'currency' => 'EUR',
                'instructions' => 'Please provide your EUR bank account details including IBAN and BIC/SWIFT code.',
                'sort_order' => 14,
                'description' => 'EUR SEPA Transfer to European bank accounts',
                'icon' => 'fas fa-euro-sign',
                'processing_time' => '1-2 business days',
                'status' => 1,
                'min_amount' => 50.00,
                'max_amount' => 45000.00,
                'daily_limit' => 12000.00,
                'charge_type' => 'fixed',
                'charge' => 20.00,
            ],
            [
                'form_id' => 0,
                'name' => 'GBP Bank Transfer',
                'method_key' => 'gbp_bank',
                'min_limit' => 40.00,
                'max_limit' => 40000.00,
                'fixed_charge' => 0.00,
                'rate' => 0.79,
                'percent_charge' => 2.50,
                'currency' => 'GBP',
                'instructions' => 'Please provide your UK bank account details including sort code and account number.',
                'sort_order' => 15,
                'description' => 'GBP Faster Payments to UK bank accounts',
                'icon' => 'fas fa-pound-sign',
                'processing_time' => '1-2 business days',
                'status' => 1,
                'min_amount' => 40.00,
                'max_amount' => 40000.00,
                'daily_limit' => 10000.00,
                'charge_type' => 'fixed',
                'charge' => 15.00,
            ],
            [
                'form_id' => 0,
                'name' => 'CAD Bank Transfer',
                'method_key' => 'cad_bank',
                'min_limit' => 60.00,
                'max_limit' => 60000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.35,
                'percent_charge' => 2.50,
                'currency' => 'CAD',
                'instructions' => 'Please provide your Canadian bank account details including transit number and account number.',
                'sort_order' => 16,
                'description' => 'CAD Wire Transfer to Canadian bank accounts',
                'icon' => 'fas fa-maple-leaf',
                'processing_time' => '1-3 business days',
                'status' => 1,
                'min_amount' => 60.00,
                'max_amount' => 60000.00,
                'daily_limit' => 15000.00,
                'charge_type' => 'fixed',
                'charge' => 30.00,
            ],
            [
                'form_id' => 0,
                'name' => 'AUD Bank Transfer',
                'method_key' => 'aud_bank',
                'min_limit' => 70.00,
                'max_limit' => 70000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.52,
                'percent_charge' => 2.50,
                'currency' => 'AUD',
                'instructions' => 'Please provide your Australian bank account details including BSB and account number.',
                'sort_order' => 17,
                'description' => 'AUD Wire Transfer to Australian bank accounts',
                'icon' => 'fas fa-dollar-sign',
                'processing_time' => '1-3 business days',
                'status' => 1,
                'min_amount' => 70.00,
                'max_amount' => 70000.00,
                'daily_limit' => 18000.00,
                'charge_type' => 'fixed',
                'charge' => 35.00,
            ],
            [
                'form_id' => 0,
                'name' => 'JPY Bank Transfer',
                'method_key' => 'jpy_bank',
                'min_limit' => 5000.00,
                'max_limit' => 7000000.00,
                'fixed_charge' => 0.00,
                'rate' => 149.50,
                'percent_charge' => 2.00,
                'currency' => 'JPY',
                'instructions' => 'Please provide your Japanese bank account details including bank code and account number.',
                'sort_order' => 18,
                'description' => 'JPY Wire Transfer to Japanese bank accounts',
                'icon' => 'fas fa-yen-sign',
                'processing_time' => '1-2 business days',
                'status' => 1,
                'min_amount' => 5000.00,
                'max_amount' => 7000000.00,
                'daily_limit' => 2000000.00,
                'charge_type' => 'fixed',
                'charge' => 2500.00,
            ],
            
            // Additional Popular Cryptocurrencies
            [
                'form_id' => 0,
                'name' => 'Solana (SOL)',
                'method_key' => 'solana',
                'min_limit' => 5.00,
                'max_limit' => 25000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 1.50,
                'currency' => 'SOL',
                'instructions' => 'Please provide your Solana wallet address.',
                'sort_order' => 19,
                'description' => 'Solana (SOL) cryptocurrency withdrawal',
                'icon' => 'fas fa-coins',
                'processing_time' => '1-3 minutes',
                'status' => 1,
                'min_amount' => 5.00,
                'max_amount' => 25000.00,
                'daily_limit' => 8000.00,
                'charge_type' => 'fixed',
                'charge' => 0.50,
            ],
            [
                'form_id' => 0,
                'name' => 'Avalanche (AVAX)',
                'method_key' => 'avalanche',
                'min_limit' => 10.00,
                'max_limit' => 30000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 2.00,
                'currency' => 'AVAX',
                'instructions' => 'Please provide your Avalanche wallet address.',
                'sort_order' => 20,
                'description' => 'Avalanche (AVAX) cryptocurrency withdrawal',
                'icon' => 'fas fa-mountain',
                'processing_time' => '1-5 minutes',
                'status' => 1,
                'min_amount' => 10.00,
                'max_amount' => 30000.00,
                'daily_limit' => 10000.00,
                'charge_type' => 'fixed',
                'charge' => 2.00,
            ],
            [
                'form_id' => 0,
                'name' => 'Dogecoin (DOGE)',
                'method_key' => 'dogecoin',
                'min_limit' => 50.00,
                'max_limit' => 100000.00,
                'fixed_charge' => 0.00,
                'rate' => 1.00,
                'percent_charge' => 1.00,
                'currency' => 'DOGE',
                'instructions' => 'Please provide your Dogecoin wallet address.',
                'sort_order' => 21,
                'description' => 'Dogecoin (DOGE) cryptocurrency withdrawal',
                'icon' => 'fas fa-dog',
                'processing_time' => '5-15 minutes',
                'status' => 1,
                'min_amount' => 50.00,
                'max_amount' => 100000.00,
                'daily_limit' => 25000.00,
                'charge_type' => 'fixed',
                'charge' => 5.00,
            ],
        ];

        foreach ($withdrawMethods as $method) {
            WithdrawMethod::create($method);
        }
    }
}
